POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "This a blog title",
  "author": "me",
  "url": "https://fullstackopen.com/",
  "likes": 100,
  "user":"root"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "the second blog title",
  "author": "me",
  "url": "https://www.google.com/",
  "likes": 100,
  "user":"root"
}